//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faculty
    {
        public int FacultyId { get; set; }
        public string FacultyFName { get; set; }
        public string FacultyLName { get; set; }
        public string FacultyPhone { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public decimal Salary { get; set; }
        public string ImageName { get; set; }
        public string ImageUrl { get; set; }
        public int DepartmentId { get; set; }
        public int CourseId { get; set; }
        public int HireId { get; set; }
    }
}
